pipeline {
    agent { label 'dockeragent' }
    stages {
        stage('Test') {
            steps {
                sh 'echo hello ${BUILD_NUMBER}'
                sh 'echo $JENKINS_URL'
            }
        }
        stage('Test python'){
            steps{
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                    python3 jenkins/example_python/tt.py
                '''
            }
        }
    }
}