FROM golang:1.22

WORKDIR /usr/src/app

CMD ["bash", "-c", "while true; do sleep 3600; done"]



#COPY go.mod go.sum ./
#RUN go mod download && go mod verify

#COPY . .
#RUN go build -v -o /usr/local/bin/app ./...

#CMD ["app"]